# Generated by Django 2.2.16 on 2022-08-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220815_2045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_title',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title_id'), name='one_review_per_title'),
        ),
    ]
