# Generated by Django 2.2.16 on 2022-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220817_0733'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_review_per_title',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='one_review_per_title'),
        ),
    ]
